In [7]:
import pandas as pd

In [8]:
print("Hello")

Hello

In [9]:
vt_pd = pd.read_csv("results-csv/vt.csv")

In [10]:
vt_pd.describe()

,#AVs,ALYac,APEX,AVG,Acronis,AhnLab-V3,Alibaba,Antiy-AVL,Arcabit,Avast,...,VirIT,Webroot,Xcitium,Yandex,Zillya,ZoneAlarm,Zoner,alibabacloud,huorong,tehtris
count,3609.000000,3609.00000,3609.0,3609.000000,3609.0,3609.0,3609.0,3609.000000,3609.000000,3609.000000,...,3609.000000,3609.0,3609.000000,3609.000000,3609.000000,3609.000000,3609.0,3609.000000,3609.000000,3609.0
mean,0.226378,0.00471,0.0,0.012746,0.0,0.0,0.0,0.007204,0.002771,0.012746,...,0.000554,0.0,0.001940,0.001385,0.001385,0.014963,0.0,0.003325,0.000831,0.0
std,1.904747,0.06848,0.0,0.112192,0.0,0.0,0.0,0.084583,0.052573,0.112192,...,0.023538,0.0,0.044004,0.037201,0.037201,0.121420,0.0,0.057575,0.028824,0.0
min,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
25%,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
50%,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
75%,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
max,29.000000,1.00000,0.0,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,...,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0

In [11]:
vt_pd.groupby(["Dataset"])["#AVs"].max()

Dataset
dataset1          29
dataset2          25
dataset3          19
dataset4          27
dataset5          28
upstream-repos    25
wolfi-apks        15
Name: #AVs, dtype: int64

In [12]:
bincapz_pd = pd.read_csv("results-csv/bincapz.csv")

In [13]:
bincapz_pd.head()

,Package name,Dataset,File path,Risk level (high/critical)
0,add-position-99.10.9,dataset1,/tmp/add-position-99.10.9.tgz3322280942/packag...,CRITICAL
1,call-with-safe-iteration-closing-99.10.13,dataset1,/tmp/call-with-safe-iteration-closing-99.10.13...,CRITICAL
2,cloudshelltest-99.10.9,dataset1,/tmp/cloudshelltest-99.10.9.tgz158501735/packa...,CRITICAL
3,ethers-4-99.10.9,dataset1,/tmp/ethers-4-99.10.9.tgz2838710383/package/in...,CRITICAL
4,event-hubs-track-1-99.10.9,dataset1,/tmp/event-hubs-track-1-99.10.9.tgz1033069866/...,CRITICAL

In [15]:
bincapz_pd.groupby(["Dataset"])["Risk level (high/critical)"].value_counts()

Dataset         Risk level (high/critical)
dataset1        CRITICAL                          8
                HIGH                              1
dataset2        HIGH                            210
                CRITICAL                         55
dataset3        HIGH                            407
                CRITICAL                         25
dataset4        HIGH                             59
                CRITICAL                         14
dataset5        CRITICAL                          2
                HIGH                              2
upstream-repos  HIGH                          13935
                CRITICAL                       3324
wolfi-apks      HIGH                          15342
                CRITICAL                       3476
Name: count, dtype: int64

In [16]:
bincapz_pd["Risk level (high/critical)"].value_counts()

Risk level (high/critical)
HIGH        29956
CRITICAL     6904
Name: count, dtype: int64

In [17]:
odb_pd = pd.read_csv("results-csv/oss-detect-backdoor.csv")

In [19]:
odb_pd['Dataset'].value_counts()

Dataset
oss-detect-backdoor    36511
dataset4                2119
dataset3                 933
dataset1                 103
dataset2                  44
Name: count, dtype: int64

In [3]:

# count files for each dataset
import os
import pandas as pd

def count_files_in_subdirectories(base_path):
    num_files = {
        'vt': {},
        'oss-detect-backdoor': {},
        'bincapz': {},
        'packj': {}
    }
    
    # Iterate through the first level of directories
    for level1 in os.listdir(base_path):
        level1_path = os.path.join(base_path, level1)
        
        if os.path.isdir(level1_path) and level1 in num_files:
            # Iterate through the second level of directories
            for level2 in os.listdir(level1_path):
                level2_path = os.path.join(level1_path, level2)
                
                if os.path.isdir(level2_path):
                    # Check if there are third level directories
                    third_level_dirs = [d for d in os.listdir(level2_path) if os.path.isdir(os.path.join(level2_path, d))]
                    
                    if third_level_dirs:
                        # Iterate through the third level of directories
                        for level3 in third_level_dirs:
                            level3_path = os.path.join(level2_path, level3)
                            
                            if os.path.isdir(level3_path):
                                # Count the number of files in the third level directory
                                if level1 == 'packj':
                                    # Only count .json files
                                    json_files = [f for f in os.listdir(level3_path) if f.endswith('.json') and os.path.isfile(os.path.join(level3_path, f))]
                                    num_files[level1][f"{level2}-{level3}"] = len(json_files)
                                else:
                                    # Count all files
                                    all_files = [f for f in os.listdir(level3_path) if os.path.isfile(os.path.join(level3_path, f))]
                                    num_files[level1][f"{level2}-{level3}"] = len(all_files)
                    else:
                        # Count the number of files in the second level directory
                        if level1 == 'packj':
                            # Only count .json files
                            json_files = [f for f in os.listdir(level2_path) if f.endswith('.json') and os.path.isfile(os.path.join(level2_path, f))]
                            num_files[level1][level2] = len(json_files)
                        else:
                            # Count all files
                            all_files = [f for f in os.listdir(level2_path) if os.path.isfile(os.path.join(level2_path, f))]
                            num_files[level1][level2] = len(all_files)
    
    return num_files


base_path = r'../scan-results'
file_counts = count_files_in_subdirectories(base_path)


df = pd.DataFrame(file_counts).fillna(0).astype(int)

# Reset the index to ensure the first row contains {level2}-{level3} or {level2}
df.reset_index(inplace=True)
df.rename(columns={'index': 'Dataset'}, inplace=True)

# Display the DataFrame
print(df)

                  Dataset    vt  oss-detect-backdoor  bincapz  packj
0             dataset1-js    20                   10       10      8
1         dataset1-python    20                   10       10     10
2           dataset1-ruby    20                   11       11     10
3             dataset2-js    18                    9        9      0
4         dataset2-python    20                   10       10      0
5           dataset2-ruby    17                    9        9      0
6             dataset3-js     9                    9        9      0
7         dataset3-python    10                   10       10      0
8           dataset3-ruby     8                    8        8      0
9             dataset4-js    10                   10       10      0
10        dataset4-python    10                   10       10      0
11          dataset4-ruby    10                   10       10      0
12               dataset5    10                   11       10      0
13         upstream-repos  1621                  718      631      0
14             wolfi-apks  1862                  516     1866      0
15      upstream-repos-js     0                    0        0    274
16  upstream-repos-python     0                    0        0    735
17    upstream-repos-ruby     0                    0        0    270

#